---
version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    runtime-versions:
      php: 7.3
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo $AWS_REGION
      - echo $CODEBUILD_BUILD_ARN
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_BUILD_IMAGE
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_KMS_KEY_ID
      - echo $CODEBUILD_LOG_PATH
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_START_TIME
      - echo $CODEBUILD_WEBHOOK_ACTOR_ACCOUNT_ID
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $HOME
      - echo Entered the install phase...
      - |
          export DEBIAN_FRONTEND=noninteractive
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php ;
          php -r "unlink('composer-setup.php');" ;
          mv composer.phar /usr/local/bin/composer
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install --no-progress --no-suggest
      
  post_build:
    commands:
      - rm -rf .git .gitignore



artifacts:
  files:
    - '**/*'
  name: app-$CODEBUILD_RESOLVED_SOURCE_VERSION.zip
